### ISSUE TITLE
Ractiveify not compatible with latest ractivejs

### ISSUE THREAD

**Issue by dkleehammer** [norcalli/ractiveify#5]
In the ractiveify package.json dependency list, the dependency is for ractivejs 0.6.x, however, the latest ractivejs is 0.7.2.  This is causing the template mismatched error.  Are there any new releases coming out soon to remedy this?

**Comment by norcalli** [comment]
What is the exact error you're getting/a quick way to replicate this? I haven't updated my ractive in a bit, so I hadn't run into problems. I'll look into updating it.

**Comment by dkleehammer** [comment]
Thanks for the quick reply, here is the error message:
Mismatched template version (expected 3, got 1)! Please ensure you are using the latest version of Ractive.js in your build process as well as in your app

**Comment by norcalli** [comment]
I'm able to reproduce. I'll try updating now.

**Comment by norcalli** [comment]
See if it works now @ 1.5.5. Sorry I lagged. Hadn't touched this in a bit.

**Comment by dkleehammer** [comment]
Working great now, thanks!
